[package]
name = "error_handling_custom_type_for_validation"
version = "0.1.0"
authors = ["Hank Wang <drapho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
