[package]
name = "playground"
version = "0.1.0"
authors = ["Hank Wang <467745+hanksudo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
